const EXTENSION_ID = 'yutengjing.vscode-fe-helper';
const EXTENSION_NAME = 'VSCodeFEHelper';
const ID_LANG_MAPPER = new Map([
    ['abap', 'ABAP'],
    ['bat', 'Windows Bat'],
    ['bibtex', 'BibTeX'],
    ['clojure', 'Clojure'],
    ['coffeescript', 'Coffeescript'],
    ['c', 'C'],
    ['cpp', 'C++'],
    ['csharp', 'C#'],
    ['css', 'CSS'],
    ['diff', 'Diff'],
    ['dockerfile', 'Dockerfile'],
    ['editorconfig', 'EditorConfig'],
    ['fsharp', 'F#'],
    ['git-commit', 'Git'],
    ['git-rebase', 'Git'],
    ['go', 'Go'],
    ['groovy', 'Groovy'],
    ['handlebars', 'Handlebars'],
    ['html', 'HTML'],
    ['ini', 'Ini'],
    ['java', 'Java'],
    ['javascript', 'JavaScript'],
    ['javascriptreact', 'JavaScript React'],
    ['json', 'JSON'],
    ['jsonc', 'JSON with Comments'],
    ['latex', 'LaTeX'],
    ['less', 'Less'],
    ['lua', 'Lua'],
    ['makefile', 'Makefile'],
    ['markdown', 'Markdown'],
    ['objective-c', 'Objective-C'],
    ['objective-cpp', 'Objective-C++'],
    ['perl', 'Perl'],
    ['perl6', 'Perl'],
    ['php', 'PHP'],
    ['plaintext', 'Plain Text'],
    ['powershell', 'PowerShell'],
    ['jade', 'Pug'],
    ['python', 'Python'],
    ['r', 'R'],
    ['razor', 'Razor (cshtml)'],
    ['ruby', 'Ruby'],
    ['rust', 'Rust'],
    ['scss', 'SCSS'],
    ['sass', 'SCSS'],
    ['shaderlab', 'ShaderLab'],
    ['shellscript', 'Shell Script (Bash)'],
    ['sql', 'SQL'],
    ['swift', 'Swift'],
    ['typescript', 'TypeScript'],
    ['typescriptreact', 'TypeScript React'],
    ['tex', 'TeX'],
    ['vb', 'Visual Basic'],
    ['vue', 'Vue'],
    ['xml', 'XML'],
    ['xsl', 'XSL'],
    ['yaml', 'YAML'],
]);

export { EXTENSION_ID, EXTENSION_NAME, ID_LANG_MAPPER };
